//
//  RedditPostFeedInjector.swift
//  RedditClientApp
//
//  Created by Andre Insigne on 12/10/2019.
//  Copyright © 2019 andreinsigne. All rights reserved.
//


import Foundation


/// injector protocol template for injection of the services and data
protocol RedditPostFeedInjector {
    func inject(viewController: RedditPostFeedViewController)
}
/// injector implementation of the protocol template for injection
class RedditPostFeedInjectorImplementation: RedditPostFeedInjector {

    /// injects the RedditPostFeedViewController generated with the services and the presenter used
    /// data
    /// - Parameter viewController: RedditPostFeedViewController generated by the mvp template
    func inject(viewController: RedditPostFeedViewController) {
     
 
        let data = DataInjector().getData()
        let services = ServicesInjector(data: data)
        let presenter = RedditPostFeedPresenterImplementation(view: viewController, apiManager : services.getAPI() , authManager : services.getAuth())
        
        viewController.presenter = presenter
    }
}
