//
//  ChooseInterestInjector.swift
//  RedditClientApp
//
//  Created by Andre Insigne on 11/10/2019.
//  Copyright © 2019 andreinsigne. All rights reserved.
//


import Foundation


/// injector protocol template for injection of the services and data
protocol ChooseInterestInjector {
    func inject(viewController: ChooseInterestViewController)
}
/// injector implementation of the protocol template for injection
class ChooseInterestInjectorImplementation: ChooseInterestInjector {

    /// injects the ChooseInterestViewController generated with the services and the presenter used
    /// data
    /// - Parameter viewController: ChooseInterestViewController generated by the mvp template
    func inject(viewController: ChooseInterestViewController) {
     
        
        let data = DataInjector().getData()
        let services = ServicesInjector(data: data)
        let presenter = ChooseInterestPresenterImplementation(view: viewController, apiManager : services.getAPI() , authManager : services.getAuth())
        
        viewController.presenter = presenter
    }
}
