//
//  RedditCommunityInjector.swift
//  RedditClientApp
//
//  Created by Andre Insigne on 12/10/2019.
//  Copyright © 2019 andreinsigne. All rights reserved.
//


import Foundation


/// injector protocol template for injection of the services and data
protocol RedditCommunityInjector {
    func inject(viewController: RedditCommunityViewController)
}
/// injector implementation of the protocol template for injection
class RedditCommunityInjectorImplementation: RedditCommunityInjector {

    /// injects the RedditCommunityViewController generated with the services and the presenter used
    /// data
    /// - Parameter viewController: RedditCommunityViewController generated by the mvp template
    func inject(viewController: RedditCommunityViewController) {
     
 
        let data = DataInjector().getData()
        let services = ServicesInjector(data: data)
        let presenter = RedditCommunityPresenterImplementation(view: viewController, apiManager : services.getAPI() , authManager : services.getAuth())
        
        viewController.presenter = presenter
    }
}
