//
//  RedditOAuthInjector.swift
//  RedditClientApp
//
//  Created by Andre Insigne on 12/10/2019.
//  Copyright © 2019 andreinsigne. All rights reserved.
//


import Foundation


/// injector protocol template for injection of the services and data
protocol RedditOAuthInjector {
    func inject(viewController: RedditOAuthViewController)
}
/// injector implementation of the protocol template for injection
class RedditOAuthInjectorImplementation: RedditOAuthInjector {

    /// injects the RedditOAuthViewController generated with the services and the presenter used
    /// data
    /// - Parameter viewController: RedditOAuthViewController generated by the mvp template
    func inject(viewController: RedditOAuthViewController) {
     
 
        let data = DataInjector().getData()
        let services = ServicesInjector(data: data)
        let presenter = RedditOAuthPresenterImplementation(view: viewController, apiManager : services.getAPI() , authManager : services.getAuth())
        
        viewController.presenter = presenter
    }
}
