//
//  RedditFilterFeedSearchInjector.swift
//  RedditClientApp
//
//  Created by Andre Insigne on 12/10/2019.
//  Copyright © 2019 andreinsigne. All rights reserved.
//


import Foundation


/// injector protocol template for injection of the services and data
protocol RedditFilterFeedSearchInjector {
    func inject(viewController: RedditFilterFeedSearchViewController)
}
/// injector implementation of the protocol template for injection
class RedditFilterFeedSearchInjectorImplementation: RedditFilterFeedSearchInjector {

    /// injects the RedditFilterFeedSearchViewController generated with the services and the presenter used
    /// data
    /// - Parameter viewController: RedditFilterFeedSearchViewController generated by the mvp template
    func inject(viewController: RedditFilterFeedSearchViewController) {
     
 
        let data = DataInjector().getData()
        let services = ServicesInjector(data: data)
        let presenter = RedditFilterFeedSearchPresenterImplementation(view: viewController, apiManager : services.getAPI() , authManager : services.getAuth())
        
        viewController.presenter = presenter
    }
}
