//
//  RedditAuthSignInjector.swift
//  RedditClientApp
//
//  Created by Andre Insigne on 12/10/2019.
//  Copyright © 2019 andreinsigne. All rights reserved.
//


import Foundation


/// injector protocol template for injection of the services and data
protocol RedditAuthSignInjector {
    func inject(viewController: RedditAuthSignViewController)
}
/// injector implementation of the protocol template for injection
class RedditAuthSignInjectorImplementation: RedditAuthSignInjector {

    /// injects the RedditAuthSignViewController generated with the services and the presenter used
    /// data
    /// - Parameter viewController: RedditAuthSignViewController generated by the mvp template
    func inject(viewController: RedditAuthSignViewController) {
        let data = DataInjector().getData()
        let services = ServicesInjector(data: data)
        let presenter = RedditAuthSignPresenterImplementation(view: viewController, apiManager : services.getAPI() , authManager : services.getAuth())
        
        viewController.presenter = presenter
    }
}
