//
//  RedditPostActionInjector.swift
//  RedditClientApp
//
//  Created by Andre Insigne on 14/10/2019.
//  Copyright © 2019 andreinsigne. All rights reserved.
//


import Foundation


/// injector protocol template for injection of the services and data
protocol RedditPostActionInjector {
    func inject(viewController: RedditPostActionViewController)
}
/// injector implementation of the protocol template for injection
class RedditPostActionInjectorImplementation: RedditPostActionInjector {

    /// injects the RedditPostActionViewController generated with the services and the presenter used
    /// data
    /// - Parameter viewController: RedditPostActionViewController generated by the mvp template
    func inject(viewController: RedditPostActionViewController) {
     
 
        let data = DataInjector().getData()
        let services = ServicesInjector(data: data)
        let presenter = RedditPostActionPresenterImplementation(view: viewController, apiManager : services.getAPI() , authManager : services.getAuth())
        
        viewController.presenter = presenter
    }
}
