//
//  RedditDetailsInjector.swift
//  RedditClientApp
//
//  Created by Andre Insigne on 15/10/2019.
//  Copyright © 2019 andreinsigne. All rights reserved.
//


import Foundation


/// injector protocol template for injection of the services and data
protocol RedditDetailsInjector {
    func inject(viewController: RedditDetailsViewController)
}
/// injector implementation of the protocol template for injection
class RedditDetailsInjectorImplementation: RedditDetailsInjector {

    /// injects the RedditDetailsViewController generated with the services and the presenter used
    /// data
    /// - Parameter viewController: RedditDetailsViewController generated by the mvp template
    func inject(viewController: RedditDetailsViewController) {
     
 
        let data = DataInjector().getData()
        let services = ServicesInjector(data: data)
        let presenter = RedditDetailsPresenterImplementation(view: viewController, apiManager : services.getAPI() , authManager : services.getAuth())
        
        viewController.presenter = presenter
    }
}
